name: 🐘 Setup Gradle
description: Gradle setup and wrapper validation

inputs:
  cache-encryption-key:
    description: Gradle Configuration Cache encryption key
    required: false
  cache-disabled:
    description: When 'true', all caching is disabled. No entries will be written to or read from the cache.
    required: false
    default: false
  gradle-home-cache-strict-match:
    description: When 'true', the action will not attempt to restore the Gradle User Home entries from other Jobs.
    required: false
    default: true

runs:
  using: composite
  steps:
    - uses: gradle/actions/setup-gradle@8379f6a1328ee0e06e2bb424dadb7b159856a326 # v4.4.0
      with:
        add-job-summary-as-pr-comment: on-failure
        cache-encryption-key: ${{ inputs.cache-encryption-key }}
        cache-disabled: ${{ inputs.cache-disabled }}
        gradle-home-cache-strict-match: ${{ inputs.gradle-home-cache-strict-match }}
