name: 🐘 Setup Gradle
description: Gradle setup and wrapper validation

inputs:
  cache-encryption-key:
    description: Gradle Configuration Cache encryption key
    required: false

runs:
  using: composite
  steps:
    - uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
      with:
        add-job-summary-as-pr-comment: on-failure
        cache-encryption-key: ${{ inputs.cache-encryption-key }}
