name: Publish Dokka to GitHub Pages

on:
  release:
    types: [ created ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    if: github.repository == 'SimonMarquis/SealedObjectInstances'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Dokka
        uses: gradle/gradle-build-action@b5126f31dbc19dd434c3269bf8c28c315e121da2 # v2.8.1
        with:
          arguments: dokkaHtml
      - uses: actions/configure-pages@v3.0.6
      - uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: 'build/dokka'
      - id: deployment
        uses: actions/deploy-pages@v2.0.4
