name: Publish Dokka to GitHub Pages

on:
  release:
    types: [ created ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    if: github.repository == 'SimonMarquis/SealedObjectInstances'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/setup-gradle
      - run: ./gradlew dokkaHtml
      - uses: actions/configure-pages@v4.0.0
      - uses: actions/upload-pages-artifact@v3.0.0
        with:
          path: 'build/dokka'
      - id: deployment
        uses: actions/deploy-pages@v4.0.3
