name: Publish to specific repositories

on:
  workflow_dispatch:
    inputs:
      MavenLocal:
        description: 'Publish to MavenLocal'
        required: true
        default: true
        type: boolean
      GitHub:
        description: 'Publish to GitHub'
        required: true
        default: false
        type: boolean
      OSSRH:
        description: 'Publish to OSSRH'
        required: true
        default: false
        type: boolean

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build
        uses: gradle/gradle-build-action@b5126f31dbc19dd434c3269bf8c28c315e121da2 # v2.8.1
        with:
          arguments: build --stacktrace
      - name: Publish to MavenLocal
        if: ${{ inputs.MavenLocal }}
        uses: gradle/gradle-build-action@b5126f31dbc19dd434c3269bf8c28c315e121da2 # v2.8.1
        with:
          arguments: publishAllPublicationsToMavenLocalRepository
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
      - name: Upload Maven artifact
        if: ${{ inputs.MavenLocal }}
        uses: actions/upload-artifact@v3
        with:
          name: maven
          path: build/.m2/repository
      - name: Publish to GitHub
        if: ${{ inputs.GitHub }}
        uses: gradle/gradle-build-action@b5126f31dbc19dd434c3269bf8c28c315e121da2 # v2.8.1
        with:
          arguments: publishAllPublicationsToGitHubRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
      - name: Publish to OSSRH
        if: ${{ inputs.OSSRH }}
        uses: gradle/gradle-build-action@b5126f31dbc19dd434c3269bf8c28c315e121da2 # v2.8.1
        with:
          arguments: publishAllPublicationsToOSSRHRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
